import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

import ProductForm from "../components/ProductForm/ProductForm";

const Admin: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Admin</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <div className="Home__navbar">
                    <div className="Home__logo">Tienda</div>
                    <Link href="/">
                        <a>Regresar a la tienda</a>
                    </Link>
                </div>
                <ProductForm method="POST" />
            </main>
        </div>
    );
};

export default Admin;
